
title: My finished projects
email:  
description: "Sharing stuff I worked on in my free time that actually worked."
baseurl: "" 
url: ""
linkedin_username: jcnecio
github_username:  jcnecio
issues_repo: jcnecio/jcnecio.github.io
# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
exclude:
  - README