
title: Jc Blog Things
email:  
description: "Just some life thoughts I'm willing to share to the world."
baseurl: "" 
url: ""
twitter_username: jcnecio
github_username:  jcnecio

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
exclude:
  - README